/*
 * slp-pkgmgr
 *
 * Copyright (c) 2000 - 2011 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Contact: Jayoun Lee <airjany@samsung.com>, Sewook Park <sewook7.park@samsung.com>,
 * Jaeho Lee <jaeho81.lee@samsung.com>, Shobhit Srivastava <shobhit.s@samsung.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */









/**
 * @file		package-manager-types.h
 * @author		Sewook Park <sewook7.park@samsung.com>
 * @version		0.1
 * @brief		This file declares slp-pkgmgr-types
 *
 * @addtogroup APPLICATION_FRAMEWORK
 * @{
 *
 * @defgroup	pacakge_manager_type
 * @section		Header to use them:
 * @code
 * #include "package-manager-types.h"
 * @endcode
 *
 * @addtogroup pacakge_manager_type
 * @{
 */

#ifndef __PKG_MANAGER_TYPES_H__
#define __PKG_MANAGER_TYPES_H__

#include <errno.h>
#include <stdbool.h>
#include <time.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @mainpage
 * 
 * This is package manager
 *
 * Packaeg manager is used to install/uninstall the packages.\n
 * package includes dpkg, java, widget, etc. and it can be added\n
 * Security is considered on current package manager\n
 * 
 */

/**
 * @file	package-manager.h
 * @brief Package Manager header
 *
 * Generated by    Sewook Park <sewook7.park@samsung.com>
 */

#define PKG_TYPE_STRING_LEN_MAX	128
#define PKG_NAME_STRING_LEN_MAX	128
#define PKG_VERSION_STRING_LEN_MAX	128
#define PKG_VALUE_STRING_LEN_MAX 512
#define PKG_URL_STRING_LEN_MAX 1024

/** 
 *@brief application's structure retrieved by package-manager
 */
typedef struct _package_manager_pkg_info_t {
	char pkg_type[PKG_TYPE_STRING_LEN_MAX];
	char pkg_name[PKG_NAME_STRING_LEN_MAX];
	char version[PKG_VERSION_STRING_LEN_MAX];
	struct _package_manager_pkg_info_t *next;
} package_manager_pkg_info_t;

typedef struct _package_manager_pkg_detail_info_t {
	char pkg_type[PKG_TYPE_STRING_LEN_MAX];
	char pkg_name[PKG_NAME_STRING_LEN_MAX];
	char version[PKG_VERSION_STRING_LEN_MAX];
	char pkg_description[PKG_VALUE_STRING_LEN_MAX];
	char min_platform_version[PKG_VERSION_STRING_LEN_MAX];
	time_t installed_time;	/* installed time it must be GMT+0 time */
	int installed_size;		/* installed total size */
	int app_size;			/* installed app size */
	int data_size;			/* data size which is made on run time */
	char optional_id[PKG_NAME_STRING_LEN_MAX]; /*package ID if exists */
	void *pkg_optional_info;
} package_manager_pkg_detail_info_t;

/** @} */

#ifdef __cplusplus
}
#endif

#endif				/* __PKG_MANAGER_TYPES_H__ */
/**
 * @}
 * @}
 */

